### ISSUE TITLE
Allow for Dedicated LED pin to be specified

### ISSUE THREAD

**Issue by LiaIsTheCutestKitten** [lukash/refloat#13]
Probably super niche but would it be possible to allow for the "Dedicated LED pin" under Specs to be specified.
![image](https://github.com/user-attachments/assets/d879dbf7-3e54-4dd9-bef3-59980adc9409)

I can't use "PPM/Servo pin" and the "Dedicated LED pin" option appears to be my fault pin as it triggers a fault notif upon selecting and writing 😅 Got a few spare IO I want to try use instead.

**Comment by lukash** [comment]
Not really possible. Not just any arbitrary GPIO pin can be used, it needs to support DMA and a timer, you need to specifically select one of the few pins that can do that and are still free on a VESC (most of these alternate function pins are already used for the VESC stuff). Then you need to know the DMA and timer hokeed up with the pin and very specifically configure the hardware on the pin for the LED driver to work.

Not sure what's your HW, if it's designed with a pin capable of this functionality and it's a production piece, I can add support for it. If it's not a production piece, I could potentially do a custom build for you...

**Comment by LiaIsTheCutestKitten** [comment]
No worries. I wasn't sure if it might be simple or something a bit more involved. Thanks for getting back <3
